# Generated by Django 5.2.6 on 2025-10-02 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eleve',
            options={'verbose_name': 'Eleve', 'verbose_name_plural': 'Eleves'},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'verbose_name': 'Enseignant', 'verbose_name_plural': 'Enseignants'},
        ),
        migrations.AlterModelOptions(
            name='matiere',
            options={'verbose_name': 'Matiere', 'verbose_name_plural': 'Matieres'},
        ),
        migrations.AlterModelOptions(
            name='niveau',
            options={'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AlterField(
            model_name='matiere',
            name='enseignant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='notes.enseignant'),
        ),
    ]
